package genstruct

import (
	"fmt"
	"reflect"
	"time"

	"github.com/dave/jennifer/jen"
)

// Generator is responsible for generating code for static struct arrays
type Generator struct {
	Config Config
	Data   any             // The primary array of structs to generate code for
	Refs   map[string]any  // Additional arrays that can be referenced
	File   *jen.File
}

// NewGenerator creates a new generator instance with support for struct references
//
// Parameters:
//   - config: Configuration options for code generation
//   - data: The primary array of structs to generate code for
//   - refs: Optional additional arrays that can be referenced by the primary data
//
// The refs parameters enable the use of struct tags with the `structgen` tag to reference
// data between structs. For example, a Post struct with a TagSlugs field can reference
// Tag structs using the tag `structgen:"TagSlugs"`.
//
// Example usage:
//
//	generator := genstruct.NewGenerator(config, posts, tags)
func NewGenerator(config Config, data any, refs ...any) *Generator {
	// Set default identifier fields if none provided
	if config.IdentifierFields == nil {
		config.IdentifierFields = []string{"ID", "Name", "Slug", "Title", "Key", "Code"}
	}
	
	// Create a map of reference datasets
	refMap := make(map[string]any)
	for i, ref := range refs {
		// Get type name for this dataset
		refType := reflect.TypeOf(ref)
		if refType.Kind() == reflect.Slice || refType.Kind() == reflect.Array {
			elemType := refType.Elem()
			if elemType.Kind() == reflect.Struct {
				refMap[elemType.Name()] = ref
			} else {
				refMap[fmt.Sprintf("Ref%d", i)] = ref
			}
		}
	}

	return &Generator{
		Config: config,
		Data:   data,
		Refs:   refMap,
		File:   jen.NewFile(config.PackageName),
	}
}

// Generate performs the code generation
func (g *Generator) Generate() error {
	g.File.PackageComment(fmt.Sprintf(
		"// Code generated by genstruct. DO NOT EDIT.\n// Package %s contains auto-generated %s data",
		g.Config.PackageName,
		g.Config.TypeName,
	))

	// Validate that we have an array or slice
	dataValue := reflect.ValueOf(g.Data)
	if dataValue.Kind() != reflect.Slice &&
		dataValue.Kind() != reflect.Array {
		return NonSliceOrArrayError{dataValue.Kind()}
	}

	// Make sure we have at least one element to analyze the type
	if dataValue.Len() == 0 {
		return EmptyError{}
	}

	// Get the type of the first element
	firstElem := dataValue.Index(0)
	if firstElem.Kind() != reflect.Struct {
		return InvalidTypeError{firstElem.Kind()}
	}

	// Generate constants for IDs if there's an ID field
	g.generateConstants(dataValue)

	// Generate variables for each struct
	g.generateVariables(dataValue)

	// Generate a slice with all structs
	g.generateSlice(dataValue)

	// Save the generated code to file
	return g.File.Save(g.Config.OutputFile)
}

// getStructIdentifier returns a string to identify this struct instance
func (g *Generator) getStructIdentifier(structValue reflect.Value) string {
	// If a custom name function is provided, use it
	if g.Config.CustomVarNameFn != nil {
		return g.Config.CustomVarNameFn(structValue)
	}

	// Try all configured identifier fields
	for _, fieldName := range g.Config.IdentifierFields {
		field := structValue.FieldByName(fieldName)
		if field.IsValid() && field.Kind() == reflect.String && field.String() != "" {
			return field.String()
		}
	}

	// Fallback 1: Look for any string field
	for i := range structValue.NumField() {
		field := structValue.Field(i)
		if field.Kind() == reflect.String && field.String() != "" {
			return field.String()
		}
	}

	// Fallback 2: Generate a name based on the type
	return fmt.Sprintf("%s-%d", g.Config.TypeName, time.Now().UnixNano())
}
